services:
  #  psql -U gorm -d users
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
#    volumes:
#      - local_postgres:/var/lib/postgresql
#      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
    networks:
      - app_network

  app:
    container_name: goApp
    build:
      context: ..
      dockerfile: ./build/app.dockerfile
    networks:
      - app_network
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always


#volumes:
#  local_postgres:
#    external: true

networks:
  app_network:
    driver: bridge