version: '3.8'
services:
  postgres:
    build:
      context: .
    ports:
      - "9920:5432"
    volumes:
      # host:docker inner path
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm

volumes:
  postgres_storage:

