name: CI tests
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    unit-tests:
      name: Unit Tests
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:16
          env:
            POSTGRES_DB=users
            POSTGRES_USER=gorm
            POSTGRES_PASSWORD=gorm
          ports:
            - "5432:5432"

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.23'
        - name: Run tests
          run: |
            make deps
            make run &
            sleep 4

        - name: Run tests
          run: make test
